accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^register/$', register_view, name="register"),
    url(r'^profile/$', profile_view, name="profile"),
    url(r'^change_password/$', change_password_view.as_view(), name="change_password"),
    #url(r'^(?P<id>\d+)/profile/$', profile_view, name='profile'),
    url(r'^logout/$', logout_view, name="logout"),
]

ik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home_view, name='home'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'


urlpatterns = [
    url(r'^index/$', post_index, name='index'),
    url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name='delete'),
]

home/views.py
from django.shortcuts import render
# from django.shortcuts import HttpResponse


# Create your views here.
def home_view(request):

    if request.user.is_authenticated:
        context = {
            'isim': 'user',

    }
    else:
        context = {
            'isim': 'quest',

    }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}IK{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/slider.css' %}">
</head>
<body>
    {% include 'header.html' %}
    {% include 'messages.html' %}
    {% block body %}
    {% endblock %}
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/slider.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-inverse navbar-fixed-top rose shadow" role="navbar">
    <div class="container">

        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'home' %}" class="navbar-brand"><span class="white">İş Portal - {{ request.user.get_full_name }}</span></a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}"><span class="white">İlan Ekle</span></a></li>
                {% endif %}
                <li><a href="{% url 'post:index' %}"><span class="white">İş İlanları</span></a></li>
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}"><span class="white">Üye Ol</span></a></li>
                    <li><a href="{% url 'accounts:login' %}"><span class="white">Giriş</span></a></li>
                {% else %}
                    <li class="dropdown1">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="white">Profil</span>
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                           <li><a href="{% url 'accounts:profile' %}">Göster</a></li>
                           <li><a href="#"><span>Düzenle</span></a></li>
                           <li><a href="{% url 'accounts:change_password' %}"><span>Şifre Değiştir</span></a></li>
                        </ul>
                      </li>

                    <li><a href="{% url 'accounts:logout' %}"><span class="white">Çıkış</span></a></li>
                {% endif %}
            </ul>
        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

    {% block body %}

        <div class="container">

            <div class="row">
                <div class="col-md-12 col-sm-12" style="margin-bottom:10px;">
                    <form role="search" method="GET" action="/post/index/?q=">
                        <div class="input-group" >
                            <input class="form-control shadow"  style="height:60px;font-size:20px;" type="text" name="q" placeholder="Buraya aradığın poziyonları yazarak sana uygun ilanları listeyebilirsin" value="{{ request.GET.q }}" >
                            <span class="input-group-btn">
                                <input class="btn rose shadow" type="submit" style="color:#fff;height:60px;height:60px;font-size:20px;" value="Ara">
                            </span>
                        </div>
                    </form>

                </div>
            </div>


            <div class="row">
                    <div class="col-md-12 col-sm-12" id="slider">
                        <div>
                           <img alt="slider" src="/static/img/slider_1.jpg">
                        </div>
                        <div>
                            <img alt="slider" src="/static/img/slider_2.jpg">
                        </div>
                        <div>
                            <img alt="slider" src="/static/img/slider_3.jpg">
                        </div>
                    </div>
            </div>
        </div>



    {% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}